version: '3.8'
services:
  redis6379:
    image: redis:6.0
    container_name: redis6379
    restart: always
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
      - TAKE_FILE_OWNERSHIP=true
    logging:
      options:
        max-size: '100m'
        max-file: '10'